server:
  port: 8090
  error:
    include:
      message: true

spring:
  application:
    name: rococo-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'


logging:
  file:
    path: ./logs/rococo-gateway
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

#rococo-userdata:
#  base-uri: 'http://127.0.0.1:8285'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-artist:
  base-uri: 'http://127.0.0.1:8282'
#rococo-museum:
#  base-uri: 'http://127.0.0.1:8283'
#rococo-painting:
#  base-uri: 'http://127.0.0.1:8284'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8090'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

#rococo-userdata:
#  base-uri: 'http://userdata.rococo.dc:8285'
rococo-front:
  base-uri: 'http://frontend.rococo.dc'
rococo-artist:
  base-uri: 'http://artist.rococo.dc:8282'
#rococo-museum:
#  base-uri: 'http://museum.rococo.dc:8283'
#rococo-painting:
#  base-uri: 'http://painting.rococo.dc:8284'
rococo-gateway:
  base-uri: 'http://gateway.rococo.dc:8090'


#server:
#  port: 8080
#
#spring:
#  application:
#    name: rococo-gateway
#  graphql:
#    graphiql:
#      enabled: true
#    schema:
#      introspection:
#        enabled: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: 'http://127.0.0.1:9000'
#  datasource:
#    url: 'jdbc:mysql://127.0.0.1:3306/rococo-gateway?serverTimezone=UTC&createDatabaseIfNotExist=true'
#    hikari:
#      connection-timeout: 20000
#      minimum-idle: 10
#      maximum-pool-size: 30
#      idle-timeout: 10000
#      max-lifetime: 1000
#      auto-commit: true
#    username: root
#    password: secret
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-version: 0
#    schemas: rococo-gateway
#    locations: classpath:db/migration/rococo-gateway
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: false
#    generate-ddl: true
#    open-in-view: false
#
#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#
#rococo-front:
#  base-uri: 'http://127.0.0.1:3000'
