server:
  port: 8080

rococo-gateway:
  base-uri: 'http://127.0.0.1:8080'

rococo-artist:
  base-uri: 'http://127.0.0.1:8282'

rococo-museum:
  base-uri: 'http://127.0.0.1:8383'

rococo-painting:
  base-uri: 'http://127.0.0.1:8484'

rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'

rococo-front:
  base-uri: 'http://127.0.0.1:3000'

spring:
  application:
    name: rococo-gateway
  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

rococo-gateway:
  base-uri: 'http://127.0.0.1:8080'
rococo-artist:
  base-uri: 'http://127.0.0.1:8282'
rococo-museum:
  base-uri: 'http://127.0.0.1:8383'
rococo-painting:
  base-uri: 'http://127.0.0.1:8484'
rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

rococo-gateway:
  base-uri: 'http://gateway.rococo.dc:8080'
rococo-artist:
  base-uri: 'http://artist.rococo.dc:8282'
rococo-museum:
  base-uri: 'http://museum.rococo.dc:8383'
rococo-painting:
  base-uri: 'http://painting.rococo.dc:8484'
rococo-userdata:
  base-uri: 'http://userdata.rococo.dc:8089'
rococo-front:
  base-uri: 'http://frontend.rococo.dc'

