services:
  rococo-all-db:
    image: postgres:15.1
    container_name: rococo-all-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_zi
      POSTGRES_PASSWORD: secret
      CREATE_DATABASES: "rococo-auth,rococo-artist,rococo-userdata,rococo-museum,rococo-painting"
      TZ: GMT+3
      PGTZ: GMT+3
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/script:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "max_prepared_transactions=100"]
    networks:
      - rococo-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - rococo-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_NAMES: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - rococo-network

  rococo.auth.dc:
    image: zveda044/rococo-auth-docker:latest
    container_name: rococo.auth.dc
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - rococo-all-db
      - kafka
    networks:
      - rococo-network

  rococo.userdata.dc:
    image: zveda044/rococo-userdata-docker:latest
    container_name: rococo.userdata.dc
    ports:
      - "8089:8089"
    depends_on:
      - rococo-all-db
      - kafka
    networks:
      - rococo-network

  rococo.artist.dc:
    image: zveda044/rococo-artist-docker:latest
    container_name: rococo.artist.dc
    ports:
      - "8282:8282"
    depends_on:
      - rococo-all-db
    networks:
      - rococo-network

  rococo.museum.dc:
    image: zveda044/rococo-museum-docker:latest
    container_name: rococo.museum.dc
    ports:
      - "8383:8383"
    depends_on:
      - rococo-all-db
    networks:
      - rococo-network

  rococo.painting.dc:
    image: zveda044/rococo-painting-docker:latest
    container_name: rococo.painting.dc
    ports:
      - "8484:8484"
    depends_on:
      - rococo-all-db
    networks:
      - rococo-network

  rococo.gateway.dc:
    image: zveda044/rococo-gateway-docker:latest
    container_name: rococo.gateway.dc
    ports:
      - "8080:8080"
    depends_on:
      - rococo.auth.dc
    networks:
      - rococo-network

networks:
  rococo-network:
    driver: bridge

volumes:
  pgdata:
