server:
  port: 9000

spring:
  application:
    name: rococo-auth
  mvc:
    log-request-details: true
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rococo-auth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
logging:
  file:
    path: ./logs/rococo-auth
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO
---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  kafka:
    bootstrap-servers: 'localhost:9092'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-auth'
    username: postgres_zi
    password: secret
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-auth:
  base-uri: 'http://127.0.0.1:9000'
oauth2:
  client-id: 'client'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  kafka:
    bootstrap-servers: 'kafka:9092'
  datasource:
    url: 'jdbc:postgresql://rococo-all-db:5432/rococo-auth'
    username: postgres_zi
    password: secret
rococo-front:
  base-uri: 'http://frontend.rococo.dc'
rococo-auth:
  base-uri: 'http://auth.rococo.dc:9000'
oauth2:
  client-id: 'client'
---
spring:
  config:
    activate:
      on-profile: 'prod'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      uri: https://vault.qa.guru
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
  kafka:
    bootstrap-servers: ${kafka.url}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
rococo-front:
  base-uri: 'https://rococo.qa.guru'
rococo-auth:
  base-uri: 'https://auth.rococo.qa.guru'
oauth2:
  client-id: ${client-id}
---
spring:
  config:
    activate:
      on-profile: 'staging'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      uri: https://vault.qa.guru
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
  kafka:
    bootstrap-servers: ${kafka.url}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
rococo-front:
  base-uri: 'https://rococo-stage.qa.guru'
rococo-auth:
  base-uri: 'https://auth.rococo-stage.qa.guru'
oauth2:
  client-id: ${client-id}
---