spring:
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
      - 'org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration'

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:rococo-artist;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: rococo
    password: password

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  cloud:
    vault:
      enabled: false