services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_zi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rococo-artist
    ports:
      - "5432:5432"
