name: e2e

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      PROFILE: docker
      COMPOSE_PROFILES: test
      PREFIX: zveda044
      ARCH: amd64
      ALLURE_DOCKER_API: ${{ secrets.ALLURE_DOCKER_API }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      EXECUTION_TYPE: github
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build backends
        run: |
          ./gradlew jibDockerBuild -x :rococo-e2e-tests:test
      - name: Pull Chrome 127
        run: |
          docker pull selenoid/vnc_chrome:127.0
      - name: Get the last commit message
        run: |
          echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> $GITHUB_ENV
      - name: Run e2e tests
        id: e2e
        run: |
          docker compose up -d
          docker ps -a
          docker wait rococo-e2e-tests
          exit_code=$(docker inspect -f '{{.State.ExitCode}}' rococo-e2e-tests)
          echo "E2E_EXIT_CODE=$exit_code" >> $GITHUB_OUTPUT
          echo "### Test logs ###"
          docker logs rococo-e2e-tests
          if [ "$exit_code" -eq "0" ]; then
            echo "Tests passed successfully!"
            exit 0
          else
            echo "Tests failed!"
            exit 1
          fi
      - name: Add comment to PR with link to allure
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const exitCode = ${{ steps.e2e.outputs.E2E_EXIT_CODE }}
            const reportUrl = 'https://allure.niffler-stage.qa.guru/api/allure-docker-service/projects/rococo_Zi/reports/latest/index.html'
            const historyUrl = 'https://allure.niffler-stage.qa.guru/allure-docker-service-ui/projects/rococo_Zi'
            const message = exitCode == '0' ?
              `✅ TEST RUN PASSED ✅ There is the [report](${reportUrl})\n🕓 All reports [history](${historyUrl})` :
              `🔴 TEST RUN FAILED 🔴 There is the [report](${reportUrl})\n🕓 All reports [history](${historyUrl})`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })